### ISSUE TITLE
Consider wrapping liburing instead

### ISSUE THREAD

**Issue by thedrow** [stbuehler/rust-io-uring#1]
Unless the license is an issue, we could save a lot of work by wrapping liburing instead of creating our own wrapper.
See http://git.kernel.dk/cgit/liburing/ for details.

**Comment by stbuehler** [comment]
When I started writing this crate, the liburing library didn't look convincing to me in the slightest bit (API + implementation).  Also I don't think there is (neither should be) anything interesting happening in the library which is worthy of wrapping.

When the syscalls and the basic structs are available in the libc crate I will consider using those.

Additionally I have to admit I'm rather disappointed in the way the kernel iouring development went, which means I lost the motivation to work on this crate.  It might be interesting for block device/file io, but the network part is just shit imho - see my monologue in the subtread https://lore.kernel.org/linux-block/a60b2461-1db0-32cf-6eb2-35f7751a04ec@stbuehler.de/.

If there is a specific aspect of the liburing API you'd like to see here, feel free to ask for it.  Maybe I misjudged liburing back then.

**Comment by thedrow** [comment]
When was the last time you took a look into liburing?
The [library interface](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L67) seems convenient and saves us from writing some of the code.
Is there a benefit for reimplementing it in Rust?

The async block device/file IO support is what I'm interested in.
Why would you need io_uring for sockets or pipes if you have `epoll`?
What's the difference?

**Comment by stbuehler** [comment]
Completion-port style saves syscalls (requires pre-allocated buffers); also it would be nice to send from files to sockets/pipes using iouring (sendfile is usually blocking on file io).

Last time I checked seems to be https://github.com/axboe/liburing/commit/39e0ebd4fc66046bf733a47aaa899a556093ebc6

Also: did you look at my code? I like my implementation (for example [`SubmissionQueue`](https://github.com/stbuehler/rust-io-uring/blob/wip/io-uring/src/lib.rs#L51)), and don't see how it would be easier without loosing the parts I like when using liburing.

And rust has proper atomics support. https://github.com/axboe/liburing/blob/master/src/include/liburing/barrier.h is just bad. I don't wanna go near that ever.

And let me clarify what my basic issue is: I don't want to wrap c libraries, and prefer code written in rust. The benefit is "implemented in a sane language". Only if a c library does interesting stuff that is hard to reimplement in rust (or simply hard to implement at all), wrapping a c library is a good option to me.

If there is a specific feature missing in the API you think would be important, let me know.  But pointing at the C API and telling me "doesn't it look nice, use it in rust" won't help.
